[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.87.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[functions]
  directory = "functions"

[[redirects]]
  from = "/workshop/rct-evaluation-in-r/*"
  status = 200
  force = true
  conditions = {Role = ["pro"]}

[[redirects]]
 from = "/workshop/rct-evaluation-in-r/*"
 to = "/.netlify/functions/redirect"
 status = 200
 force = true

